spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  cloud:
    contract:
      dev-branch-name: dev
      test-branch-name: test
      uat-branch-name: uat
      remote-repository-url: https://github.com/mehmet-melek/producer-contracts.git
      repository-path: contractRepository
      local-dev-path: ${spring.cloud.contract.repository-path}/${spring.cloud.contract.dev-branch-name}
      local-test-path: ${spring.cloud.contract.repository-path}/${spring.cloud.contract.test-branch-name}
      local-uat-path: ${spring.cloud.contract.repository-path}/${spring.cloud.contract.uat-branch-name}
      base-path: META-INF
      product-version: 0.0.1-SNAPSHOT/contracts

git:
  user: mehmetmelekk@gmail.com
  token: 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